# Global settings applied to the whole site.
[build]
  publish = "build/"
  command = "yarn build"

# Read https://www.netlify.com/docs/continuous-deployment/#deploy-contexts
# to understand how context below works.

[context.production.environment]
  REACT_APP_API_URL = "https://meu-trampo.herokuapp.com"
  REACT_APP_DOMAIN = "app.meutrampo.com"

# Deploy Preview context: All Deploy Previews (ie.PRs)
# will inherit these settings.
[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://meu-trampo.herokuapp.com"
  REACT_APP_DOMAIN = "app.meutrampo.com"

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
# By default
[context.staging.environment]
  REACT_APP_API_URL = "https://meu-trampo-dev.herokuapp.com"
  REACT_APP_DOMAIN = "staging.meutrampo.com"
